version: '3.8'
services:

  postgresqldb:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"


